@WebApplication1_HostAddress = http://localhost:60813

GET {{WebApplication1_HostAddress}}/api/weatherforecast/
Accept: application/json

###

GET {{WebApplication1_HostAddress}}/users/0d47d5e2-04b3-4c89-a792-5fcae1e5b8fc/profiles
Accept: application/json

###

POST {{WebApplication1_HostAddress}}/users/0d47d5e2-04b3-4c89-a792-5fcae1e5b8fc/profiles/admin
Accept: application/json

### LanguageExt

POST {{WebApplication1_HostAddress}}/users/0d47d5e2-04b3-4c89-a792-5fcae1e5b8fc/profiles/admin4
Accept: application/json

###

POST {{WebApplication1_HostAddress}}/users/0d47d5e2-04b3-4c89-a792-5fcae1e5b8fc/profiles/trainer
Accept: application/json

###

POST {{WebApplication1_HostAddress}}/users/0d47d5e2-04b3-4c89-a792-5fcae1e5b8fc/profiles/participant
Accept: application/json


###

#
# AuthenticationController
#

POST {{WebApplication1_HostAddress}}/api/authentication/register
Content-Type: application/json

{
    "FirstName": "Lior",
    "LastName": "Dagan",
    "Email": "lior@dagan.com",
    "Password": "Lidagan123!!"
}

###

GET {{WebApplication1_HostAddress}}/api/authentication/
Accept: application/json


